name: Build

on:
  push:
    branches: [ lol ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11%2B8/sapmachine-jdk-11.0.11-ea.8_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" "${download_url}"
    - name: Setup sapmachine JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.0.11.tar.gz
        java-version: '11.0.11'
        architecture: x64
    - name: Maven Build
      run: mvn clean install
    - name: Docker Login
      run: docker login -u testet1991 -p 1q2w3e4r~
    - name: Push XSK
      run: |
        cd releng/server
        cp -r "${JAVA_HOME}" jdk
        docker build -t testet1991/test1 --build-arg JDK_HOME="jdk" .
        docker push testet1991/test1
        cd ../../
    - name: Push XSK for SAP Cloud Foundry
      run: |
        cd releng/sap-cf
        cp -r "${JAVA_HOME}" jdk
        docker build -t testet1991/test2 --build-arg JDK_HOME="jdk" .
        docker push testet1991/test2
        cd ../../
    - name: Push XSK for SAP Kyma
      run: |
        cd releng/sap-kyma
        cp -r "${JAVA_HOME}" jdk
        docker build -t testet1991/test3 --build-arg JDK_HOME="jdk" .
        docker push testet1991/test3
        cd ../../
