name: Build

on:
  push:
    branches: [ lol ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11%2B8/sapmachine-jdk-11.0.11-ea.8_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" "${download_url}"
        tar -xzf -C ${RUNNER_TEMP} ${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz
        export JAVA_HOME=${RUNNER_TEMP}/sapmachine-jdk-11.0.11
    - name: Maven Build
      run: mvn clean install
    - name: Dodcker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push XSK
      run: |
        cd releng/server
        docker build -t dirigiblelabs/xsk --build-arg ${JAVA_HOME} Dockerfile-external-jdk .
        docker push dirigiblelabs/xsk
        cd ../../
    - name: Push XSK for SAP Cloud Foundry
      run: |
        cd releng/sap-cf
        docker build -t dirigiblelabs/xsk-cf --build-arg ${JAVA_HOME} -f Dockerfile-external-jdk .
        docker push dirigiblelabs/xsk-cf
        cd ../../
    - name: Push XSK for SAP Kyma
      run: |
        cd releng/sap-kyma
        docker build -t dirigiblelabs/xsk-kyma --build-arg ${JAVA_HOME} -f Dockerfile-external-jdk .
        docker push dirigiblelabs/xsk-kyma
        cd ../../
