name: Build

on:
  push:
    branches: [ lol ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11%2B8/sapmachine-jdk-11.0.11-ea.8_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" "${download_url}"
    - uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.0.11.tar.gz
        java-version: '11.0.0'
        architecture: x64
    - name: Maven Build
      run: |
        echo "${JAVA_HOME}"
        mvn clean install
    - name: Docker Login
      run: |
        echo ${{ secrets.DOCKER_USER }}
        docker login -u test199828 -p 1q2w3e4r~
    - name: Push XSK
      run: |
        cd releng/server
        echo "${JAVA_HOME}"
        docker build -t test199828/test1 --build-arg JDK_HOME="${JAVA_HOME}" .
        docker push test199828/test1
        cd ../../
    - name: Push XSK for SAP Cloud Foundry
      run: |
        cd releng/sap-cf
        docker build -t test199828/test2 --build-arg JDK_HOME="${JAVA_HOME}" .
        docker push test199828/test2
        cd ../../
    - name: Push XSK for SAP Kyma
      run: |
        cd releng/sap-kyma
        docker build -t test199828/test3 --build-arg JAVA_HOME="${JAVA_HOME}" .
        docker push test199828/test3
        cd ../../
